FROM node:22-alpine3.20

WORKDIR /build/vite-project
COPY vite-project/package*.json /build/vite-project/
RUN npm i

COPY vite-project/ /build/vite-project/
RUN npm run build

FROM caddy:2.8.4-alpine

COPY Caddyfile /etc/caddy/Caddyfile
COPY --from=0 /build/vite-project/dist /srv
COPY entrypoint.sh /app/entrypoint.sh
RUN chmod +x /app/entrypoint.sh

EXPOSE 80

WORKDIR /srv
CMD /app/entrypoint.sh caddy run --config /etc/caddy/Caddyfile --adapter caddyfile
