services:
  postgres:
    image: postgres:17.0
    shm_size: 128mb
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_PASSWORD: '${POSTGRES_PASS}'
      POSTGRES_DB: '${POSTGRES_DBNAME}'
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./_postgres:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d
    user: "${HOST_UID}:${HOST_GID}"
    healthcheck:
      test: "pg_isready -h postgres -U ${POSTGRES_USER}"
      interval: 10s
      timeout: 20s
      retries: 5
      start_period: 10s

  reverse-proxy:
    image: traefik:v3.6.2
    restart: unless-stopped
    command:
      - --api.insecure=true
      - --accesslog=true      
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - ${TRAEFIK_HACK}
#      - “--entryPoints.websecure.address=:443”
#      - “--certificateresolver.myresolver.acme.tlschallenge=true”
#      - “—-certificateresolver.myresolver.acme.email=temo@toro.la”
#      - “—-certificateresolver.myresolver.acme.storage=/letsencrypt/acme.json”
      - --entrypoints.web.address=:80
#      - “--entrypoints.web.http.redirections.entrypoint.to=websecure“
#      - “--entrypoints.web.http.redirections.entrypoint.scheme=https“
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - ./_letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock

  backend:
    image: ${PROJECT_NAME}/backend:latest
    build: backend
    restart: unless-stopped
    environment:
      LOG_CFG_PATH: '/app/live/log_conf.yaml'
      DB_CONNECTION: 'postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASS}@postgres:5432/${POSTGRES_DBNAME}'
      AUTH_LIFETIME_HOURS: '${AUTH_LIFETIME_HOURS}'
      PASSWORD_AUTH_TOKEN_SECRET: '${PASSWORD_AUTH_TOKEN_SECRET}'
      APP_NAME: '${APP_NAME}'
      APP_BASE_URL: '${APP_BASE_URL}'
      OPENAI_API_KEY: '${OPENAI_API_KEY}'
      OPENAI_MODEL_NAME: '${OPENAI_MODEL_NAME}'
    ports:
      - "5678:5678"
    depends_on:
      postgres:
        condition: service_healthy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=PathPrefix(`/api`)"      
      - "traefik.http.services.backend.loadbalancer.server.port=8000"
      - "traefik.http.middlewares.strip-api-prefix.stripprefix.prefixes=/api"
      - "traefik.http.routers.backend.middlewares=strip-api-prefix@docker"
    volumes:
      - ./backend:/app/live
      - ./_backend_logs:/logs
    working_dir: /app/live/src
    command: python -m debugpy --listen 0.0.0.0:5678 -m fastapi_cli dev main.py --host 0.0.0.0 --root-path /api
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://127.0.0.1:8000/openapi.json || exit 1
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 10s    

  frontend:
    image: node:22-alpine3.20
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=!PathPrefix(`/api`)"
      - "traefik.http.services.frontend.loadbalancer.server.port=5173"
    volumes:
      - ./frontend/vite-project:/app
    environment:
      APP_NAME: '${APP_NAME}'
      APP_BASE_URL: '${APP_BASE_URL}'
    working_dir: /app
    command: npm run dev -- --host 0.0.0.0
    depends_on:
      backend:
        condition: service_healthy

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - "8081:8080"
